{
  # Self-contained toolbox-image flake, embedded in the sandboxer binary and
  # built inside an ephemeral `nixos/nix` container (so the host needs only
  # docker/podman, never nix). It references ONLY public inputs — never the
  # sandboxer repo. The sandboxer binary is NOT baked in (it is a host tool);
  # egress is a separate squid sidecar built from the proxyImage output.
  #
  # WHAT is in the images lives in ./images.nix, shared verbatim with the repo's
  # root flake — this file only resolves the profile's context and hands it over.
  #
  # Inputs are rev-pinned (kept in sync with the repo's root flake.lock); the
  # builder runs `nix build --no-write-lock-file`, so no flake.lock is needed
  # here and the read-only /src mount is never written to.
  description = "sandboxer toolbox image (self-contained)";

  # llm-agents' binary cache, restated here because nix only honors the
  # nixConfig of the flake it is building — an input's nixConfig (llm-agents
  # declares this same cache) is ignored. Without it, --accept-flake-config has
  # nothing to apply and every agent compiles from source; gemini-cli's
  # ~1400-package npm-deps fetch then OOM-kills (signal 9) the builder. Keep in
  # sync with github:numtide/llm-agents.nix flake nixConfig.
  nixConfig = {
    extra-substituters = [ "https://cache.numtide.com" ];
    extra-trusted-public-keys = [
      "niks3.numtide.com-1:DTx8wZduET09hRmMtKdQDxNNthLQETkc/yaX7M4qK0g="
    ];
  };

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/64c08a7ca051951c8eae34e3e3cb1e202fe36786";
    llm-agents.url = "github:numtide/llm-agents.nix/9f92699e8439e36fdb9ef25343560a7598ebea15";
    llm-agents.inputs.nixpkgs.follows = "nixpkgs";
  };

  outputs =
    { nixpkgs, llm-agents, ... }:
    let
      systems = [
        "x86_64-linux"
        "aarch64-linux"
      ];
      forSystems = nixpkgs.lib.genAttrs systems;
    in
    {
      packages = forSystems (
        system:
        let
          # Profile customization, rendered by sandboxer into the context:
          #   ./overlay.nix — a PLAIN nixpkgs overlay (final: prev: { … };
          #     no-op stub when the profile has none), applied before any
          #     attr resolution, so image.packages may name overlay attrs;
          #   ./files.json — static text files baked at absolute paths;
          #   ./env.json   — static additions to the image's OCI env.
          pkgs = import nixpkgs {
            inherit system;
            overlays = [ (import ./overlay.nix) ];
          };
          lib = pkgs.lib;
          llmAgents = llm-agents.packages.${system};

          userFiles = lib.mapAttrsToList (path: text: pkgs.writeTextDir (lib.removePrefix "/" path) text) (
            builtins.fromJSON (builtins.readFile ./files.json)
          );
          userEnv = lib.mapAttrsToList (k: v: "${k}=${v}") (builtins.fromJSON (builtins.readFile ./env.json));

          # llm-agents package names to bake in — generated by sandboxer from
          # internal/registry/registry.json (agents with "image" != false).
          agentNames = import ./agents.nix;
          agentPkgs = lib.filter (p: p != null) (map (n: llmAgents.${n} or null) agentNames);

          # Per-profile nixpkgs attrs generated by sandboxer from a profile's
          # `tools:` packs (registry/tools.json) plus `image.packages`. Empty
          # for the default image; the file is always written, so the import is
          # unconditional. Fail-closed: an unknown attribute aborts the build,
          # and dotted paths (python3Packages.requests) resolve via attrByPath
          # AGAINST THE OVERLAID pkgs — overlay-defined attrs resolve too.
          toolNames = import ./tools.nix;
          toolPkgs = map (
            n:
            lib.attrByPath (lib.splitString "." n)
              (throw "sandboxer: unknown nixpkgs attribute '${n}' (tools/image.packages)")
              pkgs
          ) toolNames;
        in
        import ./images.nix {
          inherit
            pkgs
            agentPkgs
            toolPkgs
            userFiles
            userEnv
            ;
        }
      );
    };
}
