{
  # Self-contained toolbox-image flake, embedded in the sandboxer binary and
  # built inside an ephemeral `nixos/nix` container (so the host needs only
  # docker/podman, never nix). It references ONLY public inputs — never the
  # sandboxer repo: the sandboxer binary is injected by copy as ./sandboxer.
  #
  # Inputs are rev-pinned (kept in sync with the repo's root flake.lock); the
  # builder runs `nix build --no-write-lock-file`, so no flake.lock is needed
  # here and the read-only /src mount is never written to.
  description = "sandboxer toolbox image (self-contained)";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/64c08a7ca051951c8eae34e3e3cb1e202fe36786";
    llm-agents.url = "github:numtide/llm-agents.nix/9f92699e8439e36fdb9ef25343560a7598ebea15";
    llm-agents.inputs.nixpkgs.follows = "nixpkgs";
  };

  outputs =
    { nixpkgs, llm-agents, ... }:
    let
      systems = [
        "x86_64-linux"
        "aarch64-linux"
      ];
      forSystems = nixpkgs.lib.genAttrs systems;
    in
    {
      packages = forSystems (
        system:
        let
          pkgs = import nixpkgs { inherit system; };
          lib = pkgs.lib;
          llmAgents = llm-agents.packages.${system};

          # llm-agents package names to bake in — generated by sandboxer from
          # internal/registry/registry.json (agents with "image" != false).
          agentNames = import ./agents.nix;
          agentPkgs = lib.filter (p: p != null) (map (n: llmAgents.${n} or null) agentNames);

          # The sandboxer binary is injected by copy (./sandboxer), not built
          # from source — so this flake never needs the sandboxer repo. It also
          # serves as the `_proxy` egress sidecar inside the container.
          # autoPatchelfHook relinks it against THIS image's glibc: the host
          # binary may be dynamically linked to a different nix-store glibc; a
          # static (CGO_ENABLED=0) release binary makes the patch a no-op.
          sandboxerBin =
            pkgs.runCommand "sandboxer-bin"
              {
                nativeBuildInputs = [ pkgs.autoPatchelfHook ];
                buildInputs = [
                  pkgs.stdenv.cc.cc.lib
                  pkgs.glibc
                ];
              }
              ''
                mkdir -p $out/bin
                install -m0755 ${./sandboxer} $out/bin/sandboxer
                autoPatchelf $out/bin/sandboxer || true
              '';
        in
        {
          image = pkgs.dockerTools.buildLayeredImage {
            name = "sandboxer-toolbox";
            tag = "latest";
            maxLayers = 120;
            contents =
              (with pkgs; [
                bashInteractive
                coreutils
                git
                rsync
                jq
                curl
                cacert
                gnused
                gawk
                gnugrep
                openssh
                which
              ])
              ++ agentPkgs
              ++ [ sandboxerBin ];
            config = {
              # No Entrypoint: the launcher always passes a full command
              # (bash -lc …, sandboxer _proxy …).
              Cmd = [
                "bash"
                "-l"
              ];
              WorkingDir = "/work";
              Env = [
                "PATH=/bin"
                "SSL_CERT_FILE=${pkgs.cacert}/etc/ssl/certs/ca-bundle.crt"
                "SANDBOXER_IN_CONTAINER=1"
              ];
            };
            fakeRootCommands = ''
              mkdir -p /work /tmp /run/sandboxer
              chmod 1777 /tmp
            '';
            enableFakechroot = true; # let npm-agent postinstall scripts run
          };
        }
      );
    };
}
