{
  # Self-contained toolbox-image flake, embedded in the sandboxer binary and
  # built with host nix (BuildImageHostNix). It references ONLY public inputs —
  # never the sandboxer repo. The sandboxer binary is NOT baked in (it is a
  # host tool); egress is the microVM runner's own network policy.
  #
  # WHAT is in the images lives in ./images.nix, shared verbatim with the repo's
  # root flake — this file only resolves the profile's context and hands it over.
  #
  # Inputs are rev-pinned (kept in sync with the repo's root flake.lock); the
  # builder runs `nix build --no-write-lock-file`, so no flake.lock is needed
  # here and the read-only /src mount is never written to.
  description = "sandboxer toolbox image (self-contained)";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/f13ff45afd1bb73e640eaa08a7066dbed07e3238";
  };

  outputs =
    { nixpkgs, ... }:
    let
      systems = [
        "x86_64-linux"
        "aarch64-linux"
      ];
      forSystems = nixpkgs.lib.genAttrs systems;
    in
    {
      packages = forSystems (
        system:
        let
          # Profile customization, rendered by sandboxer into the context:
          #   ./overlay.nix — a PLAIN nixpkgs overlay (final: prev: { … };
          #     no-op stub when the profile has none), applied before any
          #     attr resolution, so image.packages may name overlay attrs;
          #   ./files.json — static text files baked at absolute paths;
          #   ./env.json   — static additions to the image's OCI env.
          #
          # Agents resolve straight from nixpkgs (prebuilt on cache.nixos.org).
          # The one agent nixpkgs does not carry — pi — is vendored beside this
          # flake and grafted in by our overlay, BEFORE the profile's overlay so
          # a profile may still override it. pi's orchestration package rides
          # along the same way (images.nix bakes it at a stable guest path).
          pkgs = import nixpkgs {
            inherit system;
            # Several agents are unfree in nixpkgs (claude-code's license is
            # proprietary); the toolbox exists to run them, so the image build
            # allows unfree wholesale rather than curating a predicate that
            # breaks on every rename.
            config.allowUnfree = true;
            overlays = [
              (final: prev: {
                pi = final.callPackage ./pi/package.nix { };
                pi-agent-orchestrator = final.callPackage ./pi-orchestrator/package.nix { };
              })
              (import ./overlay.nix)
            ];
          };
          lib = pkgs.lib;

          userFiles = lib.mapAttrsToList (path: text: pkgs.writeTextDir (lib.removePrefix "/" path) text) (
            builtins.fromJSON (builtins.readFile ./files.json)
          );
          userEnv = lib.mapAttrsToList (k: v: "${k}=${v}") (builtins.fromJSON (builtins.readFile ./env.json));

          # Agent package attrs to bake in — generated by sandboxer from
          # internal/registry/registry.json (agents with "image" != false).
          # Fail-closed like toolPkgs: a vanished attr must abort the build,
          # not silently ship an image with an agent missing.
          agentNames = import ./agents.nix;
          agentPkgs = map (
            n: pkgs.${n} or (throw "sandboxer: unknown agent package '${n}' (registry.json nixPackage)")
          ) agentNames;

          # Per-profile nixpkgs attrs generated by sandboxer from a profile's
          # `tools:` packs (registry/tools.json) plus `image.packages`. Empty
          # for the default image; the file is always written, so the import is
          # unconditional. Fail-closed: an unknown attribute aborts the build,
          # and dotted paths (python3Packages.requests) resolve via attrByPath
          # AGAINST THE OVERLAID pkgs — overlay-defined attrs resolve too.
          toolNames = import ./tools.nix;
          toolPkgs = map (
            n:
            lib.attrByPath (lib.splitString "." n)
              (throw "sandboxer: unknown nixpkgs attribute '${n}' (tools/image.packages)")
              pkgs
          ) toolNames;
        in
        import ./images.nix {
          inherit
            pkgs
            agentPkgs
            toolPkgs
            userFiles
            userEnv
            ;
        }
      );
    };
}
